### ISSUE TITLE
Problem building CutyCapt with Qt5

### ISSUE THREAD

**Issue by arndo** [hoehrmann/CutyCapt#15]
Recently CutyCapt refuses to build with Qt5 (Version 5.3.2).

```
g++ -c -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W -fPIE -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_SVG_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWebKitWidgets -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWebKit -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -o CutyCapt.o CutyCapt.cpp
CutyCapt.cpp:244:66: warning: unused parameter 'errors' [-Wunused-parameter]
 CutyCapt::handleSslErrors(QNetworkReply* reply, QList<QSslError> errors) {
                                                                  ^
CutyCapt.cpp: In member function 'void CutyCapt::saveSnapshot()':
CutyCapt.cpp:285:16: error: aggregate 'QPrinter printer' has incomplete type and cannot be defined
       QPrinter printer;
                ^
CutyCapt.cpp:286:27: error: incomplete type 'QPrinter' used in nested name specifier
       printer.setPageSize(QPrinter::A4);
                           ^
Makefile:422: recipe for target 'CutyCapt.o' failed
make: *** [CutyCapt.o] Error 1
```

I've created a patch which fixes this issue: https://gist.github.com/arndo/c629eac09d7137e281ff
